### ISSUE TITLE
Use streamers' icons ?

### ISSUE THREAD

**Issue by RaphaelRochet** [maweki/twitchlive-extension#2]
Hi, do you think we could add streamers' icons in the menu ?
I'd love also to show all active streamers' icons instead of the number !

**Comment by maweki** [comment]
That's a great idea. It might take a week or two though.

I think I'd rework the Extension that you can choose between three display modes (number, all, cycle) and for all/cycle you can decide between icon only, name only or both.

And the icon in the streamer list view is a good idea anyways.

**Comment by maweki** [comment]
For posterity and because of lack of any documentation besides arcane knowledge handed down from extension to extension:

> (2016-05-08 21:32:23) maweki:
> is there a widget like St.Icon that can hold custom images (jpeg) in the top panel of the gnome-shell?
> (2016-05-08 21:33:43) maweki:
> or can I (ab)use St.Icon to show custom images?
> (2016-05-08 21:37:14) ebassi:
> maweki: You could use a Clutter.Actor with a Clutter.Image content, and load the image data using GdkPixbuf.
> (2016-05-08 21:37:39) ebassi:
> maweki: You could also use St.TextureCache
>

**Comment by RaphaelRochet** [comment]
I would try to stick with St.Icon and create a custom icons subfolder, where I'd cache streamers' icons, named with some prefix to be sure not to create any confusion with system icons.
Icons being Jpeg, PNG or even Gif should not be a problem.

**Comment by maweki** [comment]
That was my first idea as well.

But how does one change the folder St.Icon does icon-lookup?

**Comment by RaphaelRochet** [comment]
You can add a path where Gtk will look for icons :
```Gtk.IconTheme.get_default().append_search_path(Me.dir.get_child('icons').get_path());```

**Comment by maweki** [comment]
Are you sure this works with jpegs? I don't seem to get it to work. Is there any special naming scheme?

I've put a sample jpeg into /tmp/icons, added /tmp/icons to the search path and set 'sample' as icon_name and no Icon is being shown.

**Comment by RaphaelRochet** [comment]
Did a little research : only "png" bitmap format is supported (along with "svg",  and "xpm").
Still, we can continue that way and depend on third-party package like convert (imagemagick) to make PNG's out of jpegs.
Or go the GDK way. Never tried that thought. But sounds like the right way.

**Comment by maweki** [comment]
Quite a few Streamer Icons seem already to be pngs. So St.Icon would be the easiest, given that we also can just add a fallback-icon and we're good, and we use `convert` if neccessary and possible. I think I will have finished some prototype by tomorrow.

**Comment by maweki** [comment]
I've added basic support now, lacking error/sanity checking. Feedback welcome :)

**Comment by RaphaelRochet** [comment]
Looks nice.
![capture](https://cloud.githubusercontent.com/assets/1675389/15161413/69f7f812-16fe-11e6-838b-a3654a8a16ce.png)
Can you prevent streamer name and viewer count to be ellipsized ?
( Maybe something like ``StLabel.clutter_text.ellipsize = Pango.EllipsizeMode.NONE;`` )

**Comment by maweki** [comment]
It should never be ellipsized. The algorithm is to let them all layout/fill their labels and then retrieve the max of the widths and apply it to all. This is very strange behaviour.

**Comment by maweki** [comment]
I fixed a possible race condition that might have been responsible, even though I am not sure about this behaviour. As far as I can see it, the code does not allow for stuff to be ellipsized because we only once set widths and that was obtained via Math.max

**Comment by RaphaelRochet** [comment]
Still not good :
![capture d ecran de 2016-05-10 23-10-23](https://cloud.githubusercontent.com/assets/1675389/15162656/6ff78308-1704-11e6-9f03-10d1815a6f99.png)

**Comment by maweki** [comment]
Can you add 

```
.streamer-menuitem {
  border: 1px solid #fff;
}
```

into your stylesheet.css and post a screenshot?

**Comment by RaphaelRochet** [comment]
Sure :
![capture d ecran de 2016-05-10 23-23-45](https://cloud.githubusercontent.com/assets/1675389/15163005/54691384-1706-11e6-97b4-31e761f583b1.png)

**Comment by maweki** [comment]
In which gnome-version are you living in arch-land?

**Comment by RaphaelRochet** [comment]
It's 3.20

**Comment by maweki** [comment]
I am trying to get a current Arch running in a VM but could you try add the rules

`margin-left: 0; padding-left: 0; margin-right:0; padding-right: 0;` and look whether that has any impact. It seems that the space inbetween the fields would be necessary to not ellipsize.

**Comment by RaphaelRochet** [comment]
That didn't change anything :(

**Comment by RaphaelRochet** [comment]
Hey, I was working on major code change and suddently :
![capture d ecran de 2016-05-12 10-52-18](https://cloud.githubusercontent.com/assets/1675389/15209114/a9e44d04-182f-11e6-9038-544cbf28ae1b.png)

**Comment by maweki** [comment]
This is ... strange. I am just getting my jhbuild up to date. Maybe running the newest gnome-shell with the newest clutter lets me reproduce it and I can bisect clutter maybe. But if you find the issue or a workaround in the extension's codebase, that would be fine as well.

**Comment by RaphaelRochet** [comment]
In fact, this was the promise.all().then() not working : all the size-related code wasn't run and the menu was adjusting itself.

**Comment by maweki** [comment]
Then it's either get_width reporting the wrong width, set_width setting the wrong width or both. That was the layouting idea, to let the labels layout themselves and get the maximum width over all of them and apply that across the board.

**Comment by maweki** [comment]
I might have solved the mystery. What's your font-scaling-factor in `gnome-tweak-tool`. Setting it to 1.10 results in the following: 

![bildschirmfoto von 2016-05-12 14-10-11](https://cloud.githubusercontent.com/assets/613272/15214083/5351d49a-184b-11e6-9b51-6154b1b647c6.png)

**Comment by maweki** [comment]
If this is indeed the issue, we have to read `text-scaling-factor` in `org.gnome.desktop.interface` and multiply that with the retrieved size. But I will also open an issue with clutter/investigate.

**Comment by RaphaelRochet** [comment]
Sorry, but by font-scaling factor is 1.00 !

**Comment by maweki** [comment]
I think I might have fixed it.

**Comment by RaphaelRochet** [comment]
Example without and with apply sizes :
![capture d ecran de 2016-05-12 17-42-41](https://cloud.githubusercontent.com/assets/1675389/15220766/f773fb9e-1868-11e6-8e5c-eb9bc11788ae.png)
![capture d ecran de 2016-05-12 17-41-52](https://cloud.githubusercontent.com/assets/1675389/15220767/f77c23b4-1868-11e6-8175-c1338d1a553f.png)

You can see the missing space is quite huge for "..lator 2".

**Comment by maweki** [comment]
I just don't understand how any of the retrieved sizes could be so small that set_width leads to that behaviour. And why on your system but not on mine, even with the same clutter/gnome-shell version?

If you have the time, maybe you could log the reported and set sizes, and check if they compare to the actual sizes the Widgets are set to?

**Comment by RaphaelRochet** [comment]
The size reported by get_size_info (the highlight here) :
![test](https://cloud.githubusercontent.com/assets/1675389/15221596/65083ffa-186c-11e6-9bce-29560a0f109b.png)

**Comment by RaphaelRochet** [comment]
I tried to log ``this._layout.game.get_width();`` before adding the label to the boxlayout, and it returns the same; so it's definitely about the label not computing the right width.

**Comment by maweki** [comment]
We now have a framework in place to retrieve and show streamer icons. Everything else has to be done in #12
